### PR TITLE
1.3.0: FAB changes, string changes, and a bit more

### PR DESCRIPTION
**Pull request by shiningwing**
So I've been, well, *kinda* busy over the past few days. 😅 So now I have a pretty solid update to this app made. The most noticeable of these changes is that the FAB now animates between tabs. However... it also now goes away on the log tab, with that option being moved to the menu, since that fits the Material guidelines.

Preview:  
https://gfycat.com/FrightenedThoseIrishwaterspaniel

"Avoid using floating action buttons for minor and destructive actions, including the following: Archive or Trash [...]" -Source: https://goo.gl/WXPG8R

I know this is a rather bold change, so if you're not particularly fond of it being like this, let me know and I can revert it.

I also made a new notification icon for when it blocks a call, which I feel looks a little better.

I rewrote some of the strings in the app to make them a little more clear and natural, most visibly on the dialogs for deleting the entire blacklist and log.

On the internal side, I also refactored a number of the string names to use the more standard formating (something_like_this) rather than the Java format (somethingLikeThis). I also changed most instances of "black list" (note the space) with "blacklist", which is the more common spelling.

Oh, and one more thing: I changed the colors of the "Coach" tutorial, to make them fit the app better (the blue background in particular looked kinda bad, no offense).

PS. We need open source licenses! We're breaking the licenses of most of the libraries in this app without them. I'll try to get started on that tomorrow, but of course if you want to look into that then feel free. 😃

### CODE REVIEW

**Comment by jachness** [comment]
Hi! Thanks for the update. I was busy (as usual :smile: ) and I didn't want to leave you a comment without a full review.

So, here is my comments on the updates:

* The FAB
It behaves as it should!! Now that "delete blocked calls" has been moved to the menu, it should appear only when the log tab is displayed since it it a contextual option (like delete blacklist).

* New notification icon
Fantastic!

* Strings updates and standard formating
Awesome! English is not my first language as you may already notice 

* Blue color
No offense taken! It may not be the best color but offers great contrast specially useful for visual disabilities. It also makes clear that is it a layer on top of the app. The brown color lacks all of that. Maybe another color than the brown?

* Third-party licenses
uff yes, I know. Maybe you want to take a look at this [lib](https://github.com/PSDev/LicensesDialog). I may be wrong but I think it grabs all third-party licenses automatically.

I think I covered all the updates. If you need any help just let me know.
Thank you again to take time for this update!


**PS**: I would like to notice some improvements on the pull request tool. Now we are just two but things get hard when there are multiple collaborators making changes at the same time. Here is a great [doc](https://code.tutsplus.com/articles/team-collaboration-with-github--net-29876) about the proper use of pull request (and team collaboration in general). 

The highlights point are:
* Make a new branch for every new group of features.
* It is convenient that the master branch is always in sync with the original repo master branch.
* The app version should be modify only by the repo owner.
* Avoid changing dev tool versions like the gradle version in the build.gradle file. It may break others collaborator's dev environment.

**Comment by shiningwing** [comment]
Oh, thanks for that doc and the highlight points! I'm pretty new to this stuff, so I had no idea. I'll be sure to keep it in mind in the future! Especially the points about the version number and gradle version. After this pull request is done, I'll be sure to redo my local fork.

Yeah, I was wondering about the brown color myself, after I implemented it. I'll play around with the colors (keeping it in theme, of course), and see what looks best. I'll make another commit once I've figured that out.

I was actually looking into that licenses library you linked just yesterday. It doesn't grab the licenses automatically I don't think, but it's ridiculously easy to add in the licenses yourself using it. I was trying to implement it into the app, but I'm not that experienced, so I couldn't figure it out. Maybe I need to look at it in a different way. I'll give it another shot and let you know.

<s>Once I make the commit with the color change, feel free to merge the branch!</s> **Alright, I'm done with that!** I'll work on the licenses dialog in a separate branch and make a new pull request if I figure it out. I'm happy to be working on this app! I feel like it's been a pretty good learning experience for me.

**Comment by jachness** [comment]
I'm glad that this is a good learning experience for you :smile: I'm pretty new also. This is the first time on github tools.

I propose to make use of the issues tool for the third-party license update. We can discuss there how to implement it before make a pull request. Take a look at the [doc](https://code.tutsplus.com/articles/team-collaboration-with-github--net-29876) (Tool 3: Bug Tracking). It may be outdated but should still be valid enough.

So, I'll looking forward to the new color and don't forget the "delete blocked calls" option (it should appear only when the log tab is displayed)

**Comment by shiningwing** [comment]
Alright, I got the "delete blocked calls" menu item to only appear on the log tab. It took me forever to figure out why it wasn't working... but then I discovered that I merely forgot to initialize appContext properly. Whoops. 😅 It works just fine now. Also, as I said in an edit in my post earlier, the colors are sorted out too. I'm using Green 700 at 60% opacity for the background (for comparison, Green 500 is used for the FAB and Next buttons). Feel free to merge now that these issues are sorted out!

Hmm, good idea using the Issues feature to discuss implementation before making a pull request.

**Comment by jachness** [comment]
Great!
I just realize that there is an error related to the notification icon (ic_stat_call_blocked.png). Just run the inspector code (analyze - inspect code) and you will see:

**Comment by jachness** [comment]
icons validation

**Comment by shiningwing** [comment]
Looks like there were two copies of the old version of that icon that didn't get replaced when I added the new one through Android Studio's image asset tool. I deleted all the resources for the icon and added it again, just to be sure there would be no problem. Android Studio's not giving me the warning anymore, so it should be fine now. It was just a warning anyway, it's not like it stops the app from working, but I'm at least glad it made me notice those old icons.

**Comment by jachness** [comment]
Ok, finally it is out :smile: Thank you very much!!!

I just revert the coach background color because I was not totally convinced. Let's create more test on that.

PS: by the way, did you create the blocked call notification icon by your own or you just picked it up?

**Pull request merged**
